-- 7월 아이스크림 총 주문량 + 상반기의 아이스크림 총 주문량
-- 큰 순서대로 상위 3개의 맛

SELECT HALF.FLAVOR
FROM FIRST_HALF HALF

JOIN JULY JULY
ON HALF.FLAVOR = JULY.FLAVOR

GROUP BY HALF.FLAVOR
ORDER BY HALF.TOTAL_ORDER + SUM(JULY.TOTAL_ORDER) DESC
LIMIT 3