-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
-- 결과는 카테고리명을 기준으로 오름차순 정렬
SELECT CATEGORY, SUM(SALES.SALES) AS TOTAL_SALES
FROM BOOK_SALES SALES
JOIN BOOK BOOK
ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE DATE_FORMAT(SALES.SALES_DATE, '%Y-%m') = '2022-01'

GROUP BY CATEGORY
ORDER BY CATEGORY