-- FOOD_PRODUCT와 FOOD_ORDER 테이블에서 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회
-- 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬해주세요.
SELECT PRODUCT.PRODUCT_ID, PRODUCT.PRODUCT_NAME, SUM(ORDE.AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT PRODUCT

JOIN (SELECT *
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE LIKE '2022-05%'
     ) ORDE
ON PRODUCT.PRODUCT_ID = ORDE.PRODUCT_ID

GROUP BY ORDE.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, ORDE.PRODUCT_ID